# Generated by Django 3.1.5 on 2021-01-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorwfh', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='karyawan',
            name='id',
        ),
        migrations.AlterField(
            model_name='karyawan',
            name='nik',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
