# Generated by Django 3.1.5 on 2021-01-11 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitorwfh', '0002_auto_20210111_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('masuk', models.TimeField(blank=True, null=True)),
                ('pulang', models.TimeField(blank=True, null=True)),
                ('status_absen', models.CharField(blank=True, max_length=50, null=True)),
                ('nik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitorwfh.karyawan')),
            ],
            options={
                'verbose_name': 'Absensi',
                'verbose_name_plural': 'Absensis',
            },
        ),
    ]
