# Generated by Django 3.1.5 on 2021-01-11 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitorwfh', '0003_absensi'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_job', models.CharField(blank=True, max_length=200, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField()),
                ('nik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitorwfh.karyawan')),
            ],
            options={
                'verbose_name': 'ListJob',
                'verbose_name_plural': 'ListJobs',
            },
        ),
    ]
