# Generated by Django 3.1.5 on 2021-01-18 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorwfh', '0004_listjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyawan',
            name='agama',
            field=models.CharField(blank=True, choices=[('Islam', 'Islam'), ('Kristen', 'Kristen'), ('Hindu', 'Hindu'), ('Budha', 'Budha'), ('Konghucu', 'Konghucu')], max_length=10, null=True),
        ),
    ]
