# Generated by Django 3.1.5 on 2021-01-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorwfh', '0005_auto_20210118_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='listjob',
            name='progres',
            field=models.PositiveIntegerField(blank=True, default=50, null=True),
        ),
    ]
